export function configRouter(router) {
    // normal routes
    router.map({
        // basic example
        '/': {
            name: 'index',
            component: require('./views/index.vue')
        },
        '/login': {
            name: 'login',
            component: require('./views/login.vue')
        },
        '/register': {
            name: 'register',
            component: require('./views/register.vue')
        },
        '/repsd/:tel':{
            name:'repsd',
            component:require('./views/repsd.vue')
            
        },
        '/reset':{
            name:'reset',
            component:require('./views/reset.vue')
        },
        '/setpsd':{
            name:'setpsd',
            component:require('./views/setpsd.vue')
        },
        '/userAgreement':{
            name:'userAgreement',
            component:require('./views/userAgreement.vue')
        },
        // -。- 用户资料也tm叫用户中心？？
        '/personalcenter':{
            name:'personalcenter',
            component:require('./views/personalcenter.vue'),
            subRoutes:{
                '/':{
                    name:'setHead',
                    component:require('./views/setHead.vue')
                },
                '/setName':{
                    name:'setName',
                    component:require('./views/setName.vue')
                },
                '/setPersonal':{
                    name:'setPersonal',
                    component:require('./views/setPersonal.vue')
                },
                '/setHobby':{
                    name:'setHobby',
                    component:require('./views/setHobby.vue')
                },
                '/setSign':{
                    name:'setSign',
                    component:require('./views/personalSign.vue')
                }
            }
        },
        '/actAll':{
            name:'actAll',
            component:require('./views/actAll.vue'),
            subRoutes:{
                '/dynamics':{
                    name:'dynamics',
                    component:require('./views/dynamics.vue')
                },
                
                '/penpal':{
                    name:'penpal',
                    component:require('./views/penpal.vue')
                },
                '/finding':{
                    name:'finding',
                    component:require('./views/finding.vue')
                },
                '/mail':{
                    name:'mail',
                    component:require('./views/mail.vue')
                },
                '/mailshow/:mailId':{
                    name:'mailshow',
                    component:require('./views/mailShow.vue')
                },
                 '/admin':{
                    name:'admin',
                    component:require('./views/admin.vue')
                }
            }
        },
        '/dynamics/:msgId':{
            name:'comment',
            component:require('./views/comment.vue')
        },
        '/sendAct':{
            name:'sendAct',
            component:require('./views/sendAct.vue')
        },
        '/application':{
            name:'application',
            component:require('./views/application.vue')
        },
        '/denied':{
            name:'denied',
            component:require('./views/denied.vue')
        },
        '/myNumerical':{
            name:'myNumerical',
            component:require('./views/myNumerical.vue')
        },
        '/myDynamics':{
            name:'myDynamics',
            component:require('./views/myDynamics.vue')
        },
        '/account':{
            name:'account',
            component:require('./views/account.vue')
            
        },
        '/userinfo':{
            name:'userIndex',
            component:require('./views/userIndex.vue'),
            subRoutes:{
                '/':{
                    name:'userinfo',
                    component:require('./views/userinfo.vue')
                },
                '/:userId':{
                    name:'user',
                    component:require('./views/user.vue')
                },
                '/userPhoto':{
                    name:'userPhoto',
                    component:require('./views/userPhoto.vue')
                },
                '/userName':{
                    name:'userName',
                    component:require('./views/userName.vue')
                },
                '/userSex':{
                    name:'userSex',
                    component:require('./views/userSex.vue')
                },
                '/userLocation':{
                    name:'userLocation',
                    component:require('./views/userLocation.vue')
                },
                '/userNum':{
                    name:'userNum',
                    component:require('./views/userNum.vue')
                },
                '/userZodiac':{
                    name:'userZodiac',
                    component:require('./views/userZodiac.vue')
                },
                '/userAnarchy':{
                    name:'userAnarchy',
                    component:require('./views/userAnarchy.vue')
                },
                '/userLove':{
                    name:'userLove',
                    component:require('./views/userLove.vue')
                },
                '/userNeed':{
                    name:'userNeed',
                    component:require('./views/userNeed.vue')
                },
                '/userStuAnarcha':{
                    name:'userStuAnarcha',
                    component:require('./views/userStuAnarcha.vue')
                },
                '/userSignature':{
                    name:'userSignature',
                    component:require('./views/userSignature.vue')
                }

            }
        },
        '/collection':{
            name:'collection',
            component:require('./views/collection.vue')
        },
        //意见反馈
        '/fedback':{
            name:'fedback',
            component:require('./views/fedback.vue')
        },
        '/updates':{
            name:'updates',
            component:require('./views/updates.vue')
        },
        '/setting':{
            name:'setting',
            component:require('./views/setting.vue')
        },
        '/findingResult':{
            name:'findingResult',
            component:require('./views/findingResult.vue')
        },
        '/findingSetting':{
            name:'findingSetting',
            component:require('./views/findingSetting.vue'),
            subRoutes:{
                '/':{
                    name:'findingIndex',
                    component:require('./views/findingIndex.vue')
                },
                '/setSex':{
                    name:'setSex',
                    component:require('./views/setSex.vue')
                },
                '/setAge':{
                    name:'setAge',
                    component:require('./views/setAge.vue')
                },
                '/setZodiac':{
                    name:'setZodiac',
                    component:require('./views/setZodiac.vue')
                },
                '/setAnarchy':{
                    name:'setAnarchy',
                    component:require('./views/setAnarchy.vue')
                },
                '/setDistances':{
                    name:'setDistances',
                    component:require('./views/setDistances')
                }
            }
        },
        //找熟人
        '/acquaintances':{
            name:'acquaintances',
            component:require('./views/acquaintances.vue')
        },
        //邀请熟人
        '/invited':{
            name:'invited',
            component:require('./views/invited.vue')
        },
        //看信
        '/readLetter':{
            name:'readLetter',
            component:require('./views/readLetter.vue')
        },
        //写信
        '/writeLetter':{
            name:'allLetter',
            component:require('./views/allLetter.vue'),
            subRoutes:{
                '/':{
                    name:'writeLetter',
                    component:require('./views/writeLetter.vue')
                },
                '/pullLetter/:accountphone':{
                    name:'pullLetter',
                    component:require('./views/pullLetter.vue')
                }
                
            }
        },
        
        //转发
        '/share':{
            name:'share',
            component:require('./views/share.vue')
        }
    })


}